name: gs1_barcode_parser
description: The barcode parser is a library for handling the contents of GS1 barcodes.
version: 1.0.2
homepage: https://github.com/mobui/gs1_barcode_parser

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.19.5


